steps:
  - name: Hello world action
    # with: # Set the secret as an input
    #   super_secret: ${{ secrets.SuperSecret }}
    env: # Or as an environment variable
      LIFF_ID: ${{ secrets.LIFF_ID}}